name = "chat"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
main = "./src/server.mjs"
route = { pattern = "searchparty.wedgy.games/api/*", zone_name = "wedgy.games" }

#[build]
#command = "npm i && npx webpack && npx wrangler pages deploy ./dist --project-name intro"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]

[[rules]]
type = "Data"
globs = ["**/*.html","**/*.svg","**/*.ico"]
fallthrough = false

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]
